### ISSUE TITLE
Issue with sodoku board population

### ISSUE THREAD

**Issue by binaryeric** [binaryeric/InfinitySodoku#1]
Doesn't fully populate the board- gonna have to be looked into. 
The DOM code for it sets the value attribute but this does not show up on the page CSS.

**Comment by peterlevine11** [comment]
Need to set innerHTML of table columns to respective value. Working on fix.

**Comment by peterlevine11** [comment]
see my branch for fix

**Comment by Shadowblade325** [comment]
Peter fixed the issue, just the board layout is iffy on Firefox, recommend using Chrome only.
